repo_name: lifnaja/python-for-data-engineer
site_name: Python for Data Engineering
site_url: https://lifnaja.github.io/python-for-data-engineer/
repo_url: https://github.com/lifnaja/python-for-data-engineer


theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra_javascript:
  - https://cdn.datacamp.com/dcl-react.js.gz

nav:
  - Home: index.md
  - Python:
    - Basic Python: python/basic_python.md
    - Basic Operators: python/basic_operators.md
    - List and Tuples: python/lists_tuples.md
    - Dictionaries: python/dictionaries.md
    - Function: python/function.md
    - Classes and Objects: python/classes_and_objects.md
    - Condition: python/condition.md
    - Loops: python/loops.md
    - Exception Handling: python/exception_handling.md
    - Context Manager: python/context_manager.md
    - Importing Modules: python/importing_modules.md
    - Unit Test: python/unit_test.md
    - Virtual Environment: python/virtual_environment.md
  - Pandas:
    - Intro: pandas/intro_pandas.md
    - Read and Write Data: pandas/read_and_write_tabular_data.md
    - Select subset data: pandas/select_subset_data.md
    - Plot int Pandas: pandas/plots_in_pandas.md